# Generated by Django 3.1.7 on 2021-03-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='name',
        ),
        migrations.AddField(
            model_name='map',
            name='coordinates',
            field=models.JSONField(default=dict),
        ),
    ]
