name: aison
channels:
  - defaults
dependencies:
  - python=3.8 
  - jupyterlab
  - opencv
  - matplotlib
  - tqdm
  - libarchive
  - scikit-learn
  - pip
  - pip:
      - tensorflow
      - albumentations
      - pandas
      - keras
      - streamlit